# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('names_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('672bad33-623b-46b0-9630-5a506e433dc5'), max_length=256),
        ),
    ]
